version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "8001:8001"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: ia-webgen-network